name: Build-APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Grant execute permission
      run: chmod +x ./gradlew          # make wrapper executable

    - uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.8            # same as wrapper properties

    - name: Build debug APK
    - uses: android-actions/setup-android@v3   # installs cmdline-tools, platforms, ndk + cmake
      run: ./gradlew assembleDebug     # ← SAME path:  ./gradlew

    - uses: actions/upload-artifact@v4
      with:
        name: CustomAUXViewer-debug
        path: app/build/outputs/apk/debug/app-debug.apk
