name: Build-APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Make sure gradlew is executable
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew        # adjust path if gradlew is inside CustomAuxViewer/

    # Install JDK + setup Gradle cache
    - uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.5
        cache-enabled: true

    # If your project sits in a sub-folder, cd into it:
    # working-directory: CustomAuxViewer

    - name: Build debug APK
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: CustomAUXViewer-debug
        path: app/build/outputs/apk/debug/app-debug.apk
